### ISSUE TITLE
Pull library for twitter widget into package?

### ISSUE THREAD

**Issue by BradRyan** [thespacedojo/shareit#51]
Trying to meet some security requirements right now and saw this package is pulling a script from twitter.  Could this library be pulled into the package?

<script id="twitter-wjs" src="https://platform.twitter.com/widgets.js"></script>

Straight from google's security requirements:
**Bad idea 3:**
*Let's load this tiny script from Twitter or Facebook...*

*Don't. Any scripts loaded from third-party sites gain full access to google.com. We don't know how good their security practices are, and we don't want to increase our attack surface in such a way. Keep in mind that even some of the largest and most reputable sites on the Internet have a fair number of serious flaws discovered every year; popularity itself is really not an argument.*

**Comment by queso** [comment]
I guess it is possible, can you give me a link to where this full doc is?

**Comment by queso** [comment]
Actually, I don't think this is an issue because I give you a ShareIt.init() function to pull that in if you WANT to. It isn't required.
