### ISSUE TITLE
Updating to Meteor v1.2 doesn't support less version used

### ISSUE THREAD

**Issue by BradRyan** [thespacedojo/shareit#53]
Maybe I'm doing something wrong, but Meteor update isn't letting me update to the latest version of this package.  It actually looks like it downgraded the package in an update, and now `meteor update` yields:
```
The following top-level dependencies were not updated to the very latest version
available:
 * joshowens:shareit 0.0.3 (0.3.1 is available)
```

I tried to force to the latest version with:
```
meteor remove joshownes:shareit
meteor add joshowens:shareit@=0.3.1
```

But it resulted in the following error:
```
While selecting package versions:
error: Conflict: Constraint less@1.0.5 is not satisfied by less 2.5.0_2.
Constraints on package "less":
* less@=2.5.0_2 <- top level
* less@1.0.5 <- joshowens:shareit 0.3.1
```

Any advice?

**Comment by daveeel** [comment]
+1

**Comment by pmwisdom** [comment]
All that needs to be done is to change api.versionsFrom to api.versionsFrom("METEOR@1.2");

**Comment by namsouth** [comment]
I face similar problem here

**Comment by geneparcellano** [comment]
Having the same issue. @pmwisdom Where does that change need to be made? Thanks!

**Comment by pmwisdom** [comment]
Package.js, Ill fork it and make the change for others if theres enough interest.

**Comment by pmwisdom** [comment]
Use this one : https://github.com/dolgarev/meteor-shareit/

**Comment by queso** [comment]
All these suggestions and no PR, eh? :)
