### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by AlmogRnD** [thespacedojo/shareit#54]
Getting the following error after updating to the latest meteor version 
Uncaught ReferenceError: process is not defined joshowens_shareit.js:32 Uncaught ReferenceError: process is not defined

**Comment by samcorcos** [comment]
+1

**Comment by sarkistlt** [comment]
+1

**Comment by hinkelmann** [comment]
+1

**Comment by gsabran** [comment]
+1

**Comment by stewiegaribaldi** [comment]
+1

**Comment by queso** [comment]
This seems fixed in master. Will release 1.0.0 today for this.
