### ISSUE TITLE
Debugger in ShareIt Build JS

### ISSUE THREAD

**Issue by mayvn10** [thespacedojo/shareit#57]
On a deployed app, a "debugger" gets inserted into line 322 within the following js file:

`.meteor/local/build/programs/web.browser/packages/joshowens_shareit.js`

I'm not sure why it keeps getting inserted when deploying but I manually overwrite this file and remove it for the time being.

**Comment by RamyElkest** [comment]
Indeed it is annoying, not sure why it appears :S

**Comment by queso** [comment]
I can't find it in the code, I must have had it in a local copy when I published last. I just pushed version 1.0.2, let me know if that fixes it.
